#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")" || exit

# Some variables
NPMVERSION=`grep Version debian/control | awk -F': ' '{print $2}' | sed -E 's/-[0-9]+$//'`
STARTDIR="$(pwd)"
DESTDIR="$STARTDIR/pkg"
OUTDIR="$STARTDIR/deb"

echo "Building $NPMVERSION..."

# Remove potential leftovers from a previous build
rm -rf "$DESTDIR" "$OUTDIR"

# Alter the tarball to remove sqlite3
# FIXME: Remove this, it's to simulate a pre-release with sqlite3 in optionalDependencies
curl https://registry.npmjs.org/thelounge/-/thelounge-${NPMVERSION}.tgz -o /tmp/thelounge-before.tgz
mkdir /tmp/thelounge
tar -xvzf /tmp/thelounge-before.tgz -C /tmp/thelounge
sed -i '/sqlite3/d' /tmp/thelounge/package/package.json
tar -cvzf /tmp/thelounge-after.tgz -C /tmp/thelounge package

# Install the package itself
npm install -g --no-optional --prefix "$DESTDIR/usr" /tmp/thelounge-after.tgz

# Write .thelounge_home to set correct system config directory
echo "/etc/thelounge" > "$DESTDIR/usr/lib/node_modules/thelounge/.thelounge_home"

# Install configuration/home directory
install -dm775 "$DESTDIR/etc/thelounge"
install -dm770 "$DESTDIR/etc/thelounge/users"
install -Dm660 \
	"$DESTDIR/usr/lib/node_modules/thelounge/defaults/config.js" \
	"$DESTDIR/etc/thelounge/config.js"

# Install systemd units
install -Dm644 "$STARTDIR/systemd/system.service" \
	"$DESTDIR/lib/systemd/system/thelounge.service"
install -Dm644 "$STARTDIR/systemd/user.service" \
	"$DESTDIR/usr/lib/systemd/user/thelounge.service"
install -dm755 "$DESTDIR/lib/systemd/system/multi-user.target.wants"
ln -s "../thelounge.service" \
	"$DESTDIR/lib/systemd/system/multi-user.target.wants/thelounge.service"

# Build .deb
mkdir "$DESTDIR/DEBIAN" "$OUTDIR"
cp "$STARTDIR/debian/"* "$DESTDIR/DEBIAN/"
dpkg-deb --build "$DESTDIR" "$OUTDIR"
